import type { Theme } from './types.js';

export const THEMES: Theme[] = [
  {
    id: 'library',
    name: 'Library',
    description: 'Long reads · light',
    use: 'Novel',
    swatchBg: '#f3ead7',
    swatchFg: '#1d160f',
    swatchAccent: '#7a3a20',
    fontPreview: '"Source Serif 4", serif',
    letter: 'Aa',
    mermaidTheme: 'neutral',
    isDark: false,
  },
  {
    id: 'lamplight',
    name: 'Lamplight',
    description: 'Long reads · dark',
    use: 'Novel',
    swatchBg: '#221c15',
    swatchFg: '#ebdfc4',
    swatchAccent: '#d49a4f',
    fontPreview: '"Source Serif 4", serif',
    letter: 'Aa',
    mermaidTheme: 'dark',
    isDark: true,
  },
  {
    id: 'manual',
    name: 'Manual',
    description: 'Spec / docs · light',
    use: 'Technical',
    swatchBg: '#ffffff',
    swatchFg: '#0e1116',
    swatchAccent: '#2266c4',
    fontPreview: 'Inter, sans-serif',
    letter: 'Aa',
    mermaidTheme: 'neutral',
    isDark: false,
  },
  {
    id: 'console',
    name: 'Console',
    description: 'Spec / docs · dark',
    use: 'Technical',
    swatchBg: '#161b22',
    swatchFg: '#d6dde6',
    swatchAccent: '#58a6ff',
    fontPreview: 'Inter, sans-serif',
    letter: 'Aa',
    mermaidTheme: 'dark',
    isDark: true,
  },
  {
    id: 'contrast',
    name: 'High Contrast',
    description: 'Accessibility',
    use: 'A11y',
    swatchBg: '#000000',
    swatchFg: '#ffffff',
    swatchAccent: '#ffe14a',
    fontPreview: 'Inter, sans-serif',
    letter: 'Aa',
    mermaidTheme: 'dark',
    isDark: true,
  },
];
